# Generated by Django 4.0.5 on 2024-10-02 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fabrica', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fabricante',
            name='pais',
            field=models.CharField(default='Desconocido', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='producto',
            name='f_vencimiento',
            field=models.DateField(blank=True, null=True),
        ),
    ]
