# Generated by Django 4.0.5 on 2024-10-02 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fabrica', '0002_fabricante_pais_producto_f_vencimiento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fabricante',
            name='pais',
            field=models.CharField(default='Desconocido', max_length=100),
        ),
    ]
